"""
Financial Modeling Prep (FMP) Repository

This repository handles the translation of FMP API data to existing domain entities.
It acts as a bridge between the FMP API service and the local database repositories.

Key Functions:
- Translate FMP API responses to CompanyShare entities
- Translate FMP API responses to ShareFactor entities
- Coordinate with existing repository infrastructure
- Handle data validation and transformation
"""

import logging
from datetime import datetime
from decimal import Decimal
from typing import Dict, List, Optional, Any, Union
from dataclasses import dataclass

from sqlalchemy.orm import Session

from src.domain.entities.finance.financial_assets.company_share import CompanyShare
from src.domain.entities.factor.finance.financial_assets.share_factor.share_factor import ShareFactor
from src.infrastructure.repositories.local_repo.finance.financial_assets.company_share_repository import CompanyShareRepository
from src.infrastructure.repositories.local_repo.factor.finance.financial_assets.share_factor_repository import ShareFactorRepository
from src.application.services.api_service.fmp_service.financial_modeling_prep_api_service import FinancialModelingPrepApiService

logger = logging.getLogger(__name__)


@dataclass
class FmpDataTranslation:
    """Result of FMP data translation containing domain entities"""
    company_shares: List[CompanyShare]
    share_factors: List[ShareFactor]
    errors: List[str]
    processed_count: int
    skipped_count: int


class FmpRepository:
    """
    Repository for Financial Modeling Prep API data translation and storage.
    
    This repository acts as a bridge between the FMP API service and the existing
    domain model repositories. It translates FMP API responses into domain entities
    and coordinates their storage in the local database.
    """
    
    def __init__(self, session: Session):
        """
        Initialize FMP repository with database session.
        
        Args:
            session: SQLAlchemy database session
        """
        self.session = session
        self.company_share_repo = CompanyShareRepository(session)
        self.share_factor_repo = ShareFactorRepository(session)
        
    def translate_quote_to_company_share(self, quote_data: Dict[str, Any]) -> Optional[CompanyShare]:
        """
        Translate FMP quote data to CompanyShare domain entity.
        
        Args:
            quote_data: FMP API quote response data
            
        Returns:
            CompanyShare entity or None if translation fails
            
        Example FMP quote data:
        {
            "symbol": "AAPL",
            "name": "Apple Inc.",
            "price": 195.89,
            "changesPercentage": 1.23,
            "change": 2.37,
            "dayLow": 194.12,
            "dayHigh": 196.95,
            "yearHigh": 199.62,
            "yearLow": 164.08,
            "marketCap": 3010590924800,
            "priceAvg50": 189.45,
            "priceAvg200": 181.23,
            "exchange": "NASDAQ",
            "volume": 52164471,
            "avgVolume": 47234521,
            "eps": 6.13,
            "pe": 31.96,
            "sharesOutstanding": 15376200000,
            "timestamp": 1699632000
        }
        """
        try:
            # Extract basic information
            ticker = quote_data.get('symbol', '').upper()
            if not ticker:
                logger.error("Quote data missing required symbol")
                return None
                
            # Get or create company share
            existing_shares = self.company_share_repo.get_by_ticker(ticker)
            if existing_shares:
                company_share = existing_shares[0]
                logger.debug(f"Using existing CompanyShare for {ticker}")
            else:
                # Create new company share
                company_share = CompanyShare(
                    id=None,  # Will be generated by repository
                    ticker=ticker,
                    exchange_id=self._map_exchange_to_id(quote_data.get('exchange', 'NASDAQ')),
                    company_id=1,  # Default - would need company lookup in production
                    start_date=datetime.now(),
                    end_date=None
                )
                
                # Set company name if available
                company_name = quote_data.get('name')
                if company_name:
                    company_share.set_company_name(company_name)
                    
                logger.debug(f"Created new CompanyShare for {ticker}")
            
            # Update market data
            price = quote_data.get('price')
            if price is not None:
                # Create MarketData for the share
                from src.domain.entities.finance.financial_assets.equity import MarketData
                market_data = MarketData(
                    price=Decimal(str(price)),
                    volume=quote_data.get('volume', 0),
                    timestamp=datetime.fromtimestamp(quote_data.get('timestamp', datetime.now().timestamp()))
                )
                company_share.update_market_data(market_data)
                
            return company_share
            
        except Exception as e:
            logger.error(f"Error translating quote to CompanyShare: {str(e)}")
            return None
    
    def translate_quote_to_share_factors(self, quote_data: Dict[str, Any]) -> List[ShareFactor]:
        """
        Translate FMP quote data to ShareFactor domain entities.
        
        Args:
            quote_data: FMP API quote response data
            
        Returns:
            List of ShareFactor entities
        """
        factors = []
        ticker = quote_data.get('symbol', '').upper()
        
        try:
            # Price factor
            price = quote_data.get('price')
            if price is not None:
                price_factor = ShareFactor(
                    name=f"{ticker}_PRICE",
                    group="MARKET_DATA",
                    subgroup="PRICE",
                    data_type="DECIMAL",
                    source="FMP_API",
                    definition=f"Current stock price for {ticker}"
                )
                factors.append(price_factor)
            
            # Market Cap factor
            market_cap = quote_data.get('marketCap')
            if market_cap is not None:
                market_cap_factor = ShareFactor(
                    name=f"{ticker}_MARKET_CAP",
                    group="MARKET_DATA", 
                    subgroup="VALUATION",
                    data_type="DECIMAL",
                    source="FMP_API",
                    definition=f"Market capitalization for {ticker}"
                )
                factors.append(market_cap_factor)
            
            # P/E Ratio factor
            pe_ratio = quote_data.get('pe')
            if pe_ratio is not None:
                pe_factor = ShareFactor(
                    name=f"{ticker}_PE_RATIO",
                    group="FINANCIAL_RATIOS",
                    subgroup="VALUATION",
                    data_type="DECIMAL", 
                    source="FMP_API",
                    definition=f"Price-to-earnings ratio for {ticker}"
                )
                factors.append(pe_factor)
            
            # Volume factor
            volume = quote_data.get('volume')
            if volume is not None:
                volume_factor = ShareFactor(
                    name=f"{ticker}_VOLUME",
                    group="MARKET_DATA",
                    subgroup="TRADING",
                    data_type="INTEGER",
                    source="FMP_API",
                    definition=f"Trading volume for {ticker}"
                )
                factors.append(volume_factor)
            
            # EPS factor
            eps = quote_data.get('eps')
            if eps is not None:
                eps_factor = ShareFactor(
                    name=f"{ticker}_EPS",
                    group="FINANCIAL_METRICS",
                    subgroup="PROFITABILITY",
                    data_type="DECIMAL",
                    source="FMP_API",
                    definition=f"Earnings per share for {ticker}"
                )
                factors.append(eps_factor)
            
            logger.debug(f"Created {len(factors)} factors for {ticker}")
            return factors
            
        except Exception as e:
            logger.error(f"Error translating quote to ShareFactors: {str(e)}")
            return []
    
    def translate_and_store_quote(self, quote_data: Dict[str, Any]) -> FmpDataTranslation:
        """
        Translate FMP quote data and store in local repositories.
        
        Args:
            quote_data: FMP API quote response data
            
        Returns:
            FmpDataTranslation with results and any errors
        """
        errors = []
        company_shares = []
        share_factors = []
        processed_count = 0
        skipped_count = 0
        
        try:
            # Translate to CompanyShare
            company_share = self.translate_quote_to_company_share(quote_data)
            if company_share:
                # Store CompanyShare
                stored_share = self.company_share_repo.add(company_share)
                if stored_share:
                    company_shares.append(stored_share)
                    processed_count += 1
                else:
                    errors.append(f"Failed to store CompanyShare for {quote_data.get('symbol')}")
                    skipped_count += 1
            else:
                errors.append(f"Failed to translate quote data for {quote_data.get('symbol')}")
                skipped_count += 1
            
            # Translate to ShareFactors
            factors = self.translate_quote_to_share_factors(quote_data)
            if factors:
                for factor in factors:
                    try:
                        # Note: ShareFactor storage would need to be implemented
                        # in the ShareFactorRepository - this is a placeholder
                        share_factors.append(factor)
                    except Exception as e:
                        errors.append(f"Failed to store ShareFactor {factor.name}: {str(e)}")
            
        except Exception as e:
            errors.append(f"Unexpected error in translation: {str(e)}")
            skipped_count += 1
        
        return FmpDataTranslation(
            company_shares=company_shares,
            share_factors=share_factors,
            errors=errors,
            processed_count=processed_count,
            skipped_count=skipped_count
        )
    
    def translate_and_store_quotes_batch(self, quotes_data: List[Dict[str, Any]]) -> FmpDataTranslation:
        """
        Translate and store multiple FMP quotes in batch.
        
        Args:
            quotes_data: List of FMP API quote response data
            
        Returns:
            FmpDataTranslation with aggregated results
        """
        all_company_shares = []
        all_share_factors = []
        all_errors = []
        total_processed = 0
        total_skipped = 0
        
        for quote_data in quotes_data:
            result = self.translate_and_store_quote(quote_data)
            
            all_company_shares.extend(result.company_shares)
            all_share_factors.extend(result.share_factors)
            all_errors.extend(result.errors)
            total_processed += result.processed_count
            total_skipped += result.skipped_count
        
        return FmpDataTranslation(
            company_shares=all_company_shares,
            share_factors=all_share_factors,
            errors=all_errors,
            processed_count=total_processed,
            skipped_count=total_skipped
        )
    
    def translate_profile_to_company_share(self, profile_data: Dict[str, Any]) -> Optional[CompanyShare]:
        """
        Translate FMP company profile data to CompanyShare domain entity.
        
        Args:
            profile_data: FMP API company profile response data
            
        Returns:
            CompanyShare entity or None if translation fails
            
        Example FMP profile data:
        {
            "symbol": "AAPL",
            "companyName": "Apple Inc.",
            "sector": "Technology",
            "industry": "Consumer Electronics", 
            "exchange": "NASDAQ",
            "description": "Apple Inc. designs, manufactures, and markets smartphones...",
            "ceo": "Timothy D. Cook",
            "fullTimeEmployees": 164000,
            "phone": "14089961010",
            "address": "One Apple Park Way",
            "city": "Cupertino",
            "state": "CA",
            "zip": "95014",
            "country": "US",
            "website": "https://www.apple.com"
        }
        """
        try:
            ticker = profile_data.get('symbol', '').upper()
            if not ticker:
                logger.error("Profile data missing required symbol")
                return None
            
            # Get existing share or create new one
            existing_shares = self.company_share_repo.get_by_ticker(ticker)
            if existing_shares:
                company_share = existing_shares[0]
            else:
                company_share = CompanyShare(
                    id=None,
                    ticker=ticker,
                    exchange_id=self._map_exchange_to_id(profile_data.get('exchange', 'NASDAQ')),
                    company_id=1,  # Default - would need company lookup in production
                    start_date=datetime.now(),
                    end_date=None
                )
            
            # Set company information
            company_name = profile_data.get('companyName')
            if company_name:
                company_share.set_company_name(company_name)
            
            sector = profile_data.get('sector')
            industry = profile_data.get('industry')
            if sector:
                company_share.set_sector(sector)
            if industry:
                company_share.set_industry(industry)
            
            return company_share
            
        except Exception as e:
            logger.error(f"Error translating profile to CompanyShare: {str(e)}")
            return None
    
    def _map_exchange_to_id(self, exchange: str) -> int:
        """
        Map exchange string to exchange ID.
        
        Args:
            exchange: Exchange string from FMP (e.g., 'NASDAQ', 'NYSE')
            
        Returns:
            Exchange ID (defaults to 1 if not found)
            
        Note:
            In production, this should lookup the actual exchange ID from the database
        """
        exchange_mapping = {
            'NASDAQ': 1,
            'NYSE': 2,
            'AMEX': 3,
            'TSX': 4,
            'LSE': 5,
            'FRA': 6
        }
        
        return exchange_mapping.get(exchange.upper(), 1)  # Default to 1
    
    def get_statistics(self) -> Dict[str, Any]:
        """
        Get repository statistics.
        
        Returns:
            Dictionary with statistics about translated data
        """
        try:
            total_company_shares = len(self.company_share_repo.get_all())
            
            return {
                'total_company_shares': total_company_shares,
                'supported_exchanges': list(self._get_exchange_mapping().keys()),
                'translation_capabilities': [
                    'FMP Quote -> CompanyShare',
                    'FMP Quote -> ShareFactors',
                    'FMP Profile -> CompanyShare',
                    'Batch processing'
                ]
            }
        except Exception as e:
            logger.error(f"Error getting statistics: {str(e)}")
            return {'error': str(e)}
    
    def _get_exchange_mapping(self) -> Dict[str, int]:
        """Get the exchange string to ID mapping"""
        return {
            'NASDAQ': 1,
            'NYSE': 2,
            'AMEX': 3,
            'TSX': 4,
            'LSE': 5,
            'FRA': 6
        }