from enum import Enum
from typing import Union


class SecurityType(Enum):
    """Defines the types of securities supported by the algorithm framework"""
    EQUITY = "Equity"
    FOREX = "Forex"
    OPTION = "Option"
    FUTURE = "Future"
    CRYPTO = "Crypto"
    CFD = "Cfd"
    COMMODITY = "Commodity"
    INDEX = "Index"


class Resolution(Enum):
    """Defines the resolution of market data"""
    TICK = "Tick"
    SECOND = "Second"
    MINUTE = "Minute"
    HOUR = "Hour"
    DAILY = "Daily"
    WEEKLY = "Weekly"
    MONTHLY = "Monthly"


class OrderType(Enum):
    """Defines the types of orders that can be placed"""
    MARKET = "Market"
    LIMIT = "Limit"
    STOP_MARKET = "StopMarket"
    STOP_LIMIT = "StopLimit"
    MARKET_ON_OPEN = "MarketOnOpen"
    MARKET_ON_CLOSE = "MarketOnClose"
    OPTION_EXERCISE = "OptionExercise"


class OrderStatus(Enum):
    """Defines the status of an order"""
    NEW = "New"
    SUBMITTED = "Submitted"
    PARTIALLY_FILLED = "PartiallyFilled"
    FILLED = "Filled"
    CANCELED = "Canceled"
    NONE = "None"
    CANCELED_REJECTED = "CanceledRejected"
    INVALID = "Invalid"


class OrderDirection(Enum):
    """Defines the direction of an order"""
    BUY = "Buy"
    SELL = "Sell"
    HOLD = "Hold"


class MarketDataType(Enum):
    """Defines the type of market data"""
    BASE = "Base"
    TRADE_BAR = "TradeBar"
    QUOTE_BAR = "QuoteBar"
    TICK = "Tick"
    AUXILIARY = "Auxiliary"
    OPTION_CHAIN = "OptionChain"
    FUTURES_CHAIN = "FuturesChain"


class TickType(Enum):
    """Defines the type of tick data"""
    TRADE = "Trade"
    QUOTE = "Quote"
    OPEN_INTEREST = "OpenInterest"


class LogLevel(Enum):
    """Defines logging levels"""
    TRACE = "Trace"
    DEBUG = "Debug"
    INFO = "Info"
    WARNING = "Warning"
    ERROR = "Error"
    CRITICAL = "Critical"


class OptionRight(Enum):
    """Defines option rights"""
    CALL = "Call"
    PUT = "Put"


class OptionStyle(Enum):
    """Defines option exercise styles"""
    AMERICAN = "American"
    EUROPEAN = "European"


class DataNormalizationMode(Enum):
    """Defines how historical data is normalized"""
    ADJUSTED = "Adjusted"
    RAW = "Raw"
    SPLIT_ADJUSTED = "SplitAdjusted"
    TOTAL_RETURN = "TotalReturn"


class FillType(Enum):
    """Defines how orders are filled"""
    PARTIAL = "Partial"
    COMPLETE = "Complete"


class InsightType(Enum):
    """Defines the type of insight generated by alpha models"""
    PRICE = "Price"
    VOLATILITY = "Volatility"


class InsightDirection(Enum):
    """Defines the direction of an insight"""
    UP = "Up"
    DOWN = "Down"
    FLAT = "Flat"